# Takes the categories of phishing generated by the LLM, and fuzzy deduplicates them

from wordllama import WordLlama
import csv

def import_csv_to_list(csv_file):
    rows = []
    with open(csv_file, mode='r', newline='', encoding='utf-8') as file:
        csv_reader = csv.reader(file)
        for row in csv_reader:
            rows.append(row[0])  # Assuming it's a one-column CSV, so append the first item
    return rows

# Load pre-trained embeddings (truncate dimension to 64)
wl = WordLlama.load(trunc_dim=64)

candidates = import_csv_to_list("nemotron_pulled_ideas.csv")


deduplicated_docs = wl.deduplicate(candidates, return_indices=False, threshold=0.4)

print("Number of duplicated sentences:  "+str(len(candidates)))
print("Number of de-duplicated sentences:  "+str(len(deduplicated_docs)))

#print(deduplicated_docs)

for i in deduplicated_docs:
    print(i)
